### ISSUE TITLE
有没有6.3.0.78的注册码，网上的都失效了

### ISSUE THREAD

**Issue by Innocence** [gendloop/ListaryPro#1]

**Comment by zheNezha** [comment]
这是个好问题

**Comment by gendloop** [comment]
我今天(2024-11-08)测试了目前已发布的 [v6.2.0](https://github.com/gendloop/ListaryPro/releases/tag/v6.2.0) 版本, 并未失效. 

可通过禁止 `选项/常规设置/自动检查更新` 以保证长期使用. 

至于其它版本, 在当前版本失效前, 我不会刻意寻找.
